name: CI/CD Tienda Perritos - DB

on:
  push:
    branches: [ "main" ]
    paths:
      - "db/**"
      - ".github/workflows/**"

jobs:
  build-push-deploy-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Crear archivo de comandos
        run: |
          cat > commands.json << 'EOF'
          {
            "commands": [
              "set -e",
              "cd /home/ec2-user/db",
              "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 346014945832.dkr.ecr.us-east-1.amazonaws.com",
              "docker build -t tienda-db .",
              "docker tag tienda-db:latest 346014945832.dkr.ecr.us-east-1.amazonaws.com/tienda-database:latest",
              "docker push 346014945832.dkr.ecr.us-east-1.amazonaws.com/tienda-database:latest",
              "docker stop tienda-db || true",
              "docker rm tienda-db || true",
              "docker run -d --name tienda-db -p 3306:3306 -v dbdata:/var/lib/mysql 346014945832.dkr.ecr.us-east-1.amazonaws.com/tienda-database:latest"
            ]
          }
          EOF

      - name: Build, Push y Deploy DB vía SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_DATA_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Build, push y deploy tienda-db desde EC2" \
            --parameters file://commands.json \
            --region ${{ secrets.AWS_REGION }} \
            --output text