name: CI Tienda Perritos - DB

on:
  push:
    branches: [ "main" ]
    paths:
      - "db/**"
      - ".github/workflows/**"

jobs:
  build-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Verificar carpeta DB
        run: |
          ls
          test -d db

      - name: Verificar Dockerfile
        run: |
          test -f db/Dockerfile

      - name: Build imagen DB
        run: |
          cd db
          docker build -t tienda-db .

      - name: Ver imágenes Docker
        run: |
          docker images